### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by h7amod** [jcw780/wows_ballistics#58]
can i know where to put the file in the game fils

**Comment by jcw780** [comment]
Currently, the files are stored here [jcw780/LiveGameData2](https://github.com/jcw780/LiveGameData2) 

Within this repository, the region which makes these requests occur [here](https://github.com/jcw780/wows_ballistics/blob/f0326487703a34970edcfa203ae3868c8a00e49c/src/components/ShellForms/DefaultForms.tsx#L66).
